x-airflow-common:
  &airflow-common
  build: .
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
    MLFLOW_S3_ENDPOINT_URL: http://s3:9000
    AWS_ACCESS_KEY_ID: qwerTY12345
    AWS_SECRET_ACCESS_KEY: poIuytRewq0987654321qwerty
    AWS_DEFAULT_REGION: ru-central1
  volumes:
    - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
    - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - backend

  postgres_clean:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: clean_data
    volumes:
      - postgres-clean-db-volume:/var/lib/postgresql/data
    ports:
      - "5423:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - backend

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - backend 

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - backend 


  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    # yamllint disable rule:line-length
    command:
      - -c
      - |
        if [[ -z "${AIRFLOW_UID}" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
          echo "If you are on Linux, you SHOULD follow the instructions below to set "
          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
          echo "For other operating systems you can get rid of the warning with manually created .env file:"
          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
          echo
        fi
        one_meg=1048576
        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
        disk_available=$$(df / | tail -1 | awk '{print $$4}')
        warning_resources="false"
        if (( mem_available < 4000 )) ; then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
          echo
          warning_resources="true"
        fi
        if (( cpus_available < 2 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
          echo "At least 2 CPUs recommended. You have $${cpus_available}"
          echo
          warning_resources="true"
        fi
        if (( disk_available < one_meg * 10 )); then
          echo
          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
          echo
          warning_resources="true"
        fi
        if [[ $${warning_resources} == "true" ]]; then
          echo
          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
          echo "Please follow the instructions to increase amount of resources available:"
          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
          echo
        fi
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version
    # yamllint enable rule:line-length
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    user: "0:0"
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}:/sources
    networks:
      - backend 

  s3:
      restart: always
      image: minio/minio:RELEASE.2025-07-23T15-54-02Z
      container_name: minio
      ports:
        - "9000:9000"
        - "9001:9001"
      volumes:
        - minio-data-volume:/data
      environment:
        MINIO_ROOT_USER: admin
        MINIO_ROOT_PASSWORD: admin123
      command: server /data --console-address ':9001' --address ':9000'
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
        interval: 30s
        timeout: 20s
        retries: 3
      networks:
        - frontend
        - backend 

  s3_setup:
    image: minio/mc:RELEASE.2025-07-21T05-28-08Z
    container_name: s3_setup
    depends_on:
      s3:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    entrypoint: ["/bin/sh", "-c"]
    command: 
      - |
        mc alias set myminio http://s3:9000 admin admin123

        mc admin user svcacct add \
          --access-key qwerTY12345 \
          --secret-key poIuytRewq0987654321qwerty \
          myminio admin
        mc mb myminio/mlflow-bucket/artifacts
        mc mb myminio/raw-data
    networks:
      - backend

  mlflow-service:
    image: ghcr.io/mlflow/mlflow:v2.15.1
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://s3:9000
      AWS_ACCESS_KEY_ID: qwerTY12345
      AWS_SECRET_ACCESS_KEY: poIuytRewq0987654321qwerty
      AWS_DEFAULT_REGION: ru-central1
    command:
      - bash
      - -c
      - |
        pip install boto3 --quiet
        mlflow server --host 0.0.0.0 \
            --default-artifact-root s3://mlflow-bucket/artifacts--serve-artifacts
    expose:
      - "5000"
    ports:
      - "5050:5000"
    volumes:
      - mlflow-data:/mlflow
    networks:
      - frontend
      - backend

  jupyter:
    image: jupyter/datascience-notebook:notebook-6.5.4
    expose:
      - "8888"
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter-data:/home/jovyan/
      - ./dags:/home/jovyan/dags
      - ./:/home/jovyan/project
    environment:
      MLFLOW_TRACKING_URI: http://mlflow-service:5000
      AWS_ENDPOINT_URL: http://s3:9000
      AWS_ACCESS_KEY_ID: qwerTY12345
      AWS_SECRET_ACCESS_KEY: poIuytRewq0987654321qwerty
      AWS_DEFAULT_REGION: ru-central1
    depends_on:
      - mlflow-service
    command:
      - bash
      - -c
      - |
        pip install mlflow==2.15.1 --quiet
        pip install boto3 --quiet
        start-notebook.sh --NotebookApp.token=''

  application:
    restart: always
    build: ./app_server
    container_name: app_server
    ports:
      - "5555:5555"
    command: python ./application.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - backend

  data-server:
    restart: always
    build: ./data_server
    container_name: data_server
    ports:
      - "4444:4444"
    command: python ./application.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  postgres-db-volume:
  postgres-clean-db-volume:
  mlflow-data:
  minio-data-volume:
